config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>[FirstApp]</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-inverse bg-dark">
      <a class="navbar-brand" href="#">[First_app]</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to '[One]', pages_one_path, {class: 'nav-link'} %>
          </li>
          <li class="nav-item">
            <%= link_to '[Two]', pages_two_path, {class: 'nav-link'} %>
          </li>
          <li class="nav-item">
            <%= link_to '[Three]', pages_three_path, {class: 'nav-link'} %>
          </li>
        </ul>
      </div>
    </nav>



    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Joaco Mellado Quevedo</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2>pinguin</h1>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor, in! Quibusdam cumque commodi animi iusto dolorum quam placeat, provident delectus tempora aliquam, voluptatum consectetur velit cupiditate sed? Pariatur, velit nemo?</p> 

app/views/pages/two.html.erb
<h1>Pages#two</h1>

<%= image_tag 'captura.png'%>